### ISSUE TITLE
[Question] How to build this distribution, which repos to pull, specific preparations to make etc.

### ISSUE THREAD

**Issue by Yetangitu** [Whyred-Dynamic-Development/Rom-Releases#7]
The subject says it all: how do we build this distribution, which repos should be pulled, what preparations need to be made, etc. Is there a build script or is it just a matter of syncing a repo and doing breakfast whyred/croot/brunch whyred?

**Comment by NopeNopeGuy** [comment]
Sorry for the very late response, but you are supposed to sync LineageOS and use my local manifest to clone the things and then figure out things on your own (it's a great learning experience, if you experience any trouble just hop over to my telegram, I'll help you there)

**Comment by Yetangitu** [comment]
Thanks for the reply and I'll have a go at it in a few days. I've done quite a bit of Android porting work in the 4.4 days and regularly build 'stock' LineageOS distributions but have not looked at the internals for a while now.

**Comment by Tofee** [comment]
Unfortunately, the script in rom-patches/apply.sh didn't work that well for me (also, maybe add that repo in the local manifest ?). 

Moreover, the patch `https://github.com/Whyred-Dynamic-Development/rom-patches/blob/lineage-21/hardware/qcom-caf/common/OverrideQcomHal.patch` is somehow empty, which is probably a mistake.

I ran into more issues, and in the end I didn't succeed in building the rom myself, like I did back in the days of lineage 18.1:
* line ending issue in bouquet-common-vendor.mk
* duplicate libthermalclient in vendor

Maybe there are still some local changes on your side that aren't pushed here?

**Comment by NopeNopeGuy** [comment]
Ignore the patches, those aren't supposed to be used for now, you are supposed to cherry-pick this: https://github.com/TheParasiteProject/hardware_qcom-caf_common/commit/6c4fa01a2bc05e4348a383d14cd2fcd852cd2905
I thought I pushed the line ending fix and libthermalclient duplication fix but I'll check again, thank you for reporting it

**Comment by NopeNopeGuy** [comment]
https://github.com/Whyred-Dynamic-Development/android_vendor_xiaomi_bouquet-common/commit/603713fcdbbf8b947afb2d7c3909aea1d692883a
Did you by chance clone the lineage-20 branch? Please hop on over to telegram @NopeNopeGuy
