### ISSUE TITLE
Fingerprint not functional in LineageOS 21 July Patch

### ISSUE THREAD

**Issue by FoRKsH** [Whyred-Dynamic-Development/Rom-Releases#8]
I tested the last build LineageOS 21 July Patch
but I found out fingerprint not working in twolip

- Rom installed from lineage recovery
- Reflashed persist.img
- Reflashed firmware 

nothing works 

[Update]
downgrade to May update works just fine 
but still not working in July patch after upgrading from May

**Comment by NopeNopeGuy** [comment]
Fixed
